pipeline {
    agent any

    stages {
        stage ('Build') {
            agent {
                docker {
                    image "node:20-alpine"
                }
            }

            steps {

                script {
                    // ✅ Clean the whole workspace first
                    deleteDir()
                }

                // ✅ Checkout fresh code
                checkout scm


                dir('02_deploy_react_app') {
                    sh '''
                    echo "Starting the Build process"
                    npm --version
                    node --version

                    ls -la

                    npm ci --verbose



                    npm run build

                    ls -la
                '''
                }
                
            }
        }
    }
}