pipeline {
    agent any

    stages {
        stage ('Build') {
            agent {
                docker {
                    image "node:24-alpine"
                    reuseNode true
                }
            }

            steps {

                
                dir('02_deploy_react_app') {
                    sh '''

                    deleteDir()
                    
                    echo "Starting the Build process"
                    npm --version
                    node --version

                    ls -la

                    npm install

                    npm run build

                    ls -la
                '''
                }
                
            }
        }
    }
}
