pipeline {
    agent any

    stages {
        stage ('Build') {
            agent {
                docker {
                    image "node:20-alpine"
                }
            }
            steps {
                dir('02_deploy_react_app')
                sh '''
                    echo "Starting the Build process"
                    npm --version
                    node --version

                    ls -la

                    npm ci

                    npm run build

                    ls -la
                '''
            }
        }
    }
}