pipeline {
    agent {
        docker { 
            image 'node:20-alpine'  }
    }
    
    environment {
        BACKEND_CONTAINER = "jenkins-backend" // container name
        NPM_CONFIG_CACHE = "${WORKSPACE}/.npm-cache"
    }
    
    stages {
        stage ('Backend') {
            steps {
                dir('01_jenkins_nodejs/backend') {
                    sh '''
                        echo "Installing necessary dependencies"
                        apk add --no-cache curl
                        npm install
                        
                        echo "Building runtime image for container"

                        cat > Dockerfile <<'EOF'
                        FROM node:20-alpine
                        WORKDIR /app
                        COPY . .
                        RUN npm install
                        CMD ["npm", "start"]
                        EOF

                        docker build -t backend-image

                        echo "Starting backend container"
                        docker run -d --name $BACKEND_CONTAINER -p 3000:3000 backend-image

                        echo "Waiting for server to start..."
                        sleep 5

                        curl -v http://localhost:3000 || echo "Server not reachable"
                        
                    '''
                }
            }
        }
        
        }
        
    post {
        always {
            echo "Pipeline finished. Backend container is running in detached mode."
        }
    }
}
